version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3406:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/mysql:/var/lib/mysql
  web: &web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RAILS_ENV: development
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    environment:
      EDITOR: vi
      MYSQL_ROOT_PASSWORD: password
      RAILS_ENV: development
      RAILS_SERVE_STATIC_FILES: 'true'
      RAILS_LOG_TO_STDOUT: 'true'
    ports:
      - 3100:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"
  webpack:
    <<: *web
    command: bin/webpack-dev-server
    ports:
      - 3135:3035
    depends_on:
      - web
volumes:
  bundle:
    driver: local
